name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 1.9.2
          - 1.9.3
          - 2.0.0
          - 2.1.8
          - 2.2.4
          - 2.3.0
          - 2.6.x

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby }} 
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Build and test with RSpec
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec
